export const ACTION_TYPES = {
  FETCH_BANKS: "FETCH_BANKS",
  FETCH_BANKS_SUCCESS: "FETCH_BANKS_SUCCESS",
  FETCH_BANKS_FAILURE: "FETCH_BANKS_FAILURE",
  FETCH_FIATS: "FETCH_FIATS",
  FETCH_FIATS_SUCCESS: "FETCH_FIATS_SUCCESS",
  FETCH_FIATS_FAILURE: "FETCH_FIATS_FAILURE",
};
